language: go
go:
  - 1.12.x
sudo: false
install:
  - go get -v github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  - export GO111MODULE=on
  - go build
  - golangci-lint run --disable-all --deadline=10m
    --enable=gofmt
    --enable=golint
    --enable=vet
    --enable=gosimple
    --enable=unconvert
