sudo: required

services:
  - docker

language: go
go:
  - 1.10.x
install:
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - gometalinter --vendor --disable-all
    --enable=gofmt
    --enable=golint
    --enable=vet
    --enable=gosimple
    --enable=unconvert
    --deadline=10m ./...
  - go build
  - docker build -t decred/dcrwebapi .
