sudo: required

services:
  - docker

language: go
go:
  - 1.11.x
install:
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export GO111MODULE=on
  - go build
  - go mod vendor
  - unset GO111MODULE
  - gometalinter --vendor --disable-all
    --enable=gofmt
    --enable=golint
    --enable=vet
    --enable=gosimple
    --enable=unconvert
    --deadline=10m ./...
  - docker build -t decred/dcrwebapi .
